name: Deploy Serverless Application

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2
  STACK_NAME: crypto-price-project
  TABLE_NAME: CryptoPriceSearchHistory
  SES_EMAIL: qianxtang@gmail.com
  ENVIRONMENT: development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli
          sam --version

      - name: Build and Deploy with SAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          sam build
          sam deploy --stack-name $STACK_NAME --region $AWS_REGION --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --parameter-overrides TableName=$TABLE_NAME SesEmail=$SES_EMAIL Environment=$ENVIRONMENT